# Copyright 2014-2016 CyberVision, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Run Kaa IoT using PostgreSQL and MongoDB

version: '2'
services:
  sql:
    image: postgres:9.4
    networks:
      - back-tier
    volumes:
      - sql-data:/var/lib/postgresql/data/kaa-pgdata
    env_file: postgres-example.env
    environment:
      - PGDATA=/var/lib/postgresql/data/kaa-pgdata # Fixes FS volume issues
  zookeeper:
    image: jplock/zookeeper:3.4.8
    networks:
      - back-tier
    volumes:
      - zookeeper-data:/tmp/zookeeper
  nosql:
    image: mongo:3.2
    networks:
      - back-tier
    volumes:
      - nosql-data:/data/db
  kaa:
    image: kaaproject/kaa:0.9.0
    # build: .
    env_file: ../kaa-example.env
    environment:
      - SQL_PROVIDER_NAME=postgresql
      - SERVICES_WAIT_TIMEOUT=-1 # Wait forever for Zookeeper and SQL
    depends_on:
      - sql
      - nosql
      - zookeeper
    networks:
      - back-tier
      - front-tier
    ports:
      - "8080:8080"
      - "9888:9888"
      - "9889:9889"
      - "9997:9997"
      - "9999:9999"
networks:
  back-tier:
    driver: bridge # overlay for Swarm (unreleased update)
  front-tier:
    driver: bridge # overlay for Swarm (unreleased update)
volumes:
  sql-data:
  nosql-data:
  zookeeper-data:
